ErrorCode = {
    UNAUTHORIZED: 1,
    EMAIL_ALREADY_IN_USE: 2,
    INVALID_EMAIL_ADDRESS: 3,
    INVALID_FIRST_NAME: 4,
    INVALID_LAST_NAME: 5,
    INTERNAL_ERROR: 6,
    ASSERTION_FAILED: 7,
    INVALID_API_KEY: 8,
    DEVICE_ALREADY_EXIST: 9,
    COMPONENT_ALREADY_EXIST: 10,
    INVALID_DATA_SUPPLIED: 11,
    DEVICE_NOT_FOUND: 12,
    FRIEND_NOT_FOUND: 13,
    USER_ALREADY_HAS_DEVICE_ACCESS: 14,
    INVALID_DEVICE_ACCESS: 15
}